### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by zjq0455** [DD-DuDa/BitDistiller#6]
Hello, thank you for your contributions!
 CUDA OUT OF MEMORY occurs when running asymmetric clipping (LLaMA-2-7B) on a single A800-80G where in your paper a single A100 is enough. Why this happened?

**Comment by DD-DuDa** [comment]
Can you share some debug information? Usually, clipping should only consume less than 5 GB of GPU memory.

**Comment by zjq0455** [comment]
> Can you share some debug information? Usually, clipping should only consume less than 5 GB of GPU memory.

~/BitDistiller/quantization# CUDA_VISIBLE_DEVICES=4 python autoclip.py --model_path /share/Llama-2-7b-hf --calib_dataset pile --quant_type int --w_bit 2 --q_group_size 128 --run_clip --dump_clip ./clip_cache/hf-llama2-7b/int2-g128.pt
Quantization config: {'zero_point': True, 'q_group_size': 128, 'quant_type': 'int'}
* Building model /share/Llama-2-7b-hf
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  2.26it/s]
Using pile dataset to do calibation
Repo card metadata block was not found. Setting CardData to empty.
Downloading data files: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 7598.38it/s]
Extracting data files: 100%|██████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.34s/it]
Generating validation split: 214670 examples [00:10, 20465.98 examples/s]
/root/anaconda3/envs/onebit/lib/python3.11/site-packages/datasets/table.py:1421: FutureWarning: promote has been superseded by promote_options='default'.
  table = cls._concat_blocks(blocks, axis=0)
Map: 100%|████████████████████████████████████████████████████████████████████████████| 214670/214670 [00:10<00:00, 20181.84 examples/s]
 * Split into 32 blocks
Running Asymmetric Clipping...:   0%|                                                                            | 0/32 [00:00<?, ?it/s]loss: 1.4379620552062988e-06
loss: 4.172325134277344e-07
loss: 9.894371032714844e-06
loss: 8.702278137207031e-06
loss: 3.725290298461914e-07
Running Asymmetric Clipping...:   3%|██▏                                                                 | 1/32 [01:12<37:29, 72.57s/it]loss: 6.258487701416016e-06
loss: 1.6689300537109375e-06
loss: 3.075599670410156e-05
loss: 2.753734588623047e-05
loss: 0.000530242919921875
Running Asymmetric Clipping...:   6%|████▎                                                               | 2/32 [02:24<36:09, 72.32s/it]loss: 9.72747802734375e-05
loss: 7.636845111846924e-07
loss: 6.389617919921875e-05
loss: 5.507469177246094e-05
loss: 1.55717134475708e-06
Running Asymmetric Clipping...:   9%|██████▍                                                             | 3/32 [03:36<34:53, 72.17s/it]loss: 0.00016498565673828125
loss: 1.6316771507263184e-06
loss: 0.00010633468627929688
loss: 8.916854858398438e-05
loss: 1.862645149230957e-06
Running Asymmetric Clipping...:  12%|████████▌                                                           | 4/32 [04:48<33:38, 72.10s/it]loss: 0.00016498565673828125
loss: 3.337860107421875e-06
loss: 0.0001621246337890625
loss: 0.00012111663818359375
loss: 7.152557373046875e-06
Running Asymmetric Clipping...:  16%|██████████▋                                                         | 5/32 [06:00<32:26, 72.08s/it]loss: 0.00022125244140625
loss: 6.735324859619141e-06
loss: 0.00019168853759765625
loss: 0.00014972686767578125
loss: 5.066394805908203e-06
Running Asymmetric Clipping...:  19%|████████████▊                                                       | 6/32 [07:12<31:14, 72.09s/it]loss: 0.0002918243408203125
loss: 8.463859558105469e-06
loss: 0.0002536773681640625
loss: 0.00018215179443359375
loss: 7.510185241699219e-06
Running Asymmetric Clipping...:  22%|██████████████▉                                                     | 7/32 [08:25<30:04, 72.17s/it]loss: 0.000438690185546875
loss: 1.239776611328125e-05
loss: 0.0002880096435546875
loss: 0.00021266937255859375
loss: 1.0251998901367188e-05
Running Asymmetric Clipping...:  25%|█████████████████                                                   | 8/32 [09:37<28:54, 72.27s/it]loss: 0.0003662109375
loss: 1.823902130126953e-05
loss: 0.000301361083984375
loss: 0.00023174285888671875
loss: 1.245737075805664e-05
Running Asymmetric Clipping...:  28%|███████████████████▏                                                | 9/32 [10:49<27:42, 72.28s/it]loss: 0.00030517578125
loss: 2.4557113647460938e-05
loss: 0.0003147125244140625
loss: 0.0002574920654296875
loss: 1.4603137969970703e-05
Running Asymmetric Clipping...:  31%|████████████████████▉                                              | 10/32 [12:02<26:31, 72.36s/it]loss: 0.000446319580078125
loss: 3.3855438232421875e-05
loss: 0.0003452301025390625
loss: 0.00026702880859375
loss: 1.6927719116210938e-05
Running Asymmetric Clipping...:  34%|███████████████████████                                            | 11/32 [13:14<25:20, 72.39s/it]loss: 0.0005645751953125
loss: 3.62396240234375e-05
loss: 0.0003376007080078125
loss: 0.0002899169921875
loss: 1.9550323486328125e-05
Running Asymmetric Clipping...:  38%|█████████████████████████▏                                         | 12/32 [14:27<24:07, 72.39s/it]loss: 0.0005035400390625
loss: 4.1961669921875e-05
loss: 0.0003566741943359375
loss: 0.000324249267578125
loss: 2.205371856689453e-05
Running Asymmetric Clipping...:  41%|███████████████████████████▏                                       | 13/32 [15:39<22:54, 72.36s/it]loss: 0.000545501708984375
loss: 4.506111145019531e-05
loss: 0.000385284423828125
loss: 0.0003490447998046875
loss: 2.7060508728027344e-05
Running Asymmetric Clipping...:  44%|█████████████████████████████▎                                     | 14/32 [16:51<21:41, 72.33s/it]loss: 0.000782012939453125
loss: 5.0067901611328125e-05
loss: 0.0004119873046875
loss: 0.000377655029296875
loss: 3.24249267578125e-05
Running Asymmetric Clipping...:  47%|███████████████████████████████▍                                   | 15/32 [18:04<20:29, 72.31s/it]loss: 0.0006866455078125
loss: 5.435943603515625e-05
loss: 0.000453948974609375
loss: 0.00042724609375
loss: 4.00543212890625e-05
Running Asymmetric Clipping...:  50%|█████████████████████████████████▌                                 | 16/32 [19:16<19:16, 72.29s/it]loss: 0.000873565673828125
loss: 7.62939453125e-05
loss: 0.000514984130859375
loss: 0.0004749298095703125
loss: 8.296966552734375e-05
Running Asymmetric Clipping...:  53%|███████████████████████████████████▌                               | 17/32 [20:28<18:04, 72.28s/it]loss: 0.000682830810546875
loss: 5.2928924560546875e-05
loss: 0.0005645751953125
loss: 0.000522613525390625
loss: 6.151199340820312e-05
Running Asymmetric Clipping...:  56%|█████████████████████████████████████▋                             | 18/32 [21:40<16:51, 72.28s/it]loss: 0.00074005126953125
loss: 6.151199340820312e-05
loss: 0.0006561279296875
loss: 0.000576019287109375
loss: 7.343292236328125e-05
Running Asymmetric Clipping...:  59%|███████████████████████████████████████▊                           | 19/32 [22:53<15:39, 72.28s/it]loss: 0.0009918212890625
loss: 5.269050598144531e-05
loss: 0.0006866455078125
loss: 0.000614166259765625
loss: 9.250640869140625e-05
Running Asymmetric Clipping...:  62%|█████████████████████████████████████████▉                         | 20/32 [24:05<14:27, 72.27s/it]loss: 0.000888824462890625
loss: 6.4849853515625e-05
loss: 0.000743865966796875
loss: 0.000659942626953125
loss: 9.72747802734375e-05
Running Asymmetric Clipping...:  66%|███████████████████████████████████████████▉                       | 21/32 [25:17<13:15, 72.28s/it]loss: 0.00107574462890625
loss: 5.745887756347656e-05
loss: 0.0008087158203125
loss: 0.000698089599609375
loss: 9.965896606445312e-05
Running Asymmetric Clipping...:  69%|██████████████████████████████████████████████                     | 22/32 [26:30<12:02, 72.29s/it]loss: 0.0011138916015625
loss: 6.914138793945312e-05
loss: 0.000888824462890625
loss: 0.00074005126953125
loss: 0.00010967254638671875
Running Asymmetric Clipping...:  72%|████████████████████████████████████████████████▏                  | 23/32 [27:43<10:50, 72.30s/it]
Traceback (most recent call last):
  File "/root/BitDistiller/quantization/autoclip.py", line 265, in <module>
    main(args, q_config)
  File "/root/BitDistiller/quantization/autoclip.py", line 219, in main
    clip_results = run_clip(
                   ^^^^^^^^^
  File "/root/anaconda3/envs/onebit/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/BitDistiller/quantization/autoclip.py", line 182, in run_clip
    inps = layer(inps, **layer_kwargs)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/onebit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/OneBit/transformers/src/transformers/models/llama/modeling_llama.py", line 657, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
                                                          ^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/onebit/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/OneBit/transformers/src/transformers/models/llama/modeling_llama.py", line 391, in forward
    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query_states.dtype)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/onebit/lib/python3.11/site-packages/torch/nn/functional.py", line 1845, in softmax
    ret = input.softmax(dim, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.00 GiB (GPU 0; 79.15 GiB total capacity; 59.86 GiB already allocated; 1.72 GiB free; 76.91 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by zjq0455** [comment]
> Can you share some debug information? Usually, clipping should only consume less than 5 GB of GPU memory.

Memory increases here in each iteration: 

inps = inps.to(next(layer.parameters()).device)  # in case multi-gpu
        # get output as next layer's input
        inps = layer(inps, **layer_kwargs)[0]
        for h in handles:
            h.remove()
        input_feat = {k: torch.cat(v, dim=0) for k, v in input_feat.items()}

**Comment by DD-DuDa** [comment]
Thank you for your question. We have found that the newest version of transformers does have this problem. 
Please use the previous version instead: 
`pip install transformers==4.31.0`

**Comment by zjq0455** [comment]
> Thank you for your question. We have found that the newest version of transformers does have this problem. Please use the previous version instead: `pip install transformers==4.31.0`

Thanks for your response, I have fixed the problem.
